name: Hello World Workflow

on:
  push:            # æ¯æ¬¡ push åˆ° repo æœƒè§¸ç™¼
    branches: [ main ]

jobs:
  hello-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Say Hello
        run: echo "Hello, World! from GitHub Actions ğŸš€"
